### ISSUE TITLE
email pack getting error in k8s ha

### ISSUE THREAD

**Issue by lingaswamy143** [StackStorm-Exchange/stackstorm-email#50]
stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/python_runner/python_action_wrapper.py", line 395, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/python_runner/python_action_wrapper.py", line 214, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/email/actions/send_email.py", line 54, in run
    s = SMTP(account_data['server'], int(account_data['port']), timeout=20)
  File "/usr/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
socket.timeout: timed out

**Comment by nzlosh** [comment]
socket timed out is a networking issue not a bug with the pack.  If you think there is a problem with the kubernetes st2 base setup, you should open an issue in https://github.com/StackStorm/stackstorm-k8s
